name: appsec_poc

on: 
  workflow_dispatch:

jobs:
  Build:

    runs-on: ubuntu-latest
    
    steps:

      - name: Check out Code
        uses: actions/checkout@v3

      - name: echoing the file name
        run: echo $GITHUB_WORKFLOW:$GITHUB_RUN_ID
        
      - name: Building Docker Images
        run: |
          docker image build -t $GITHUB_WORKFLOW:$GITHUB_RUN_ID . 
          docker image tag $GITHUB_WORKFLOW:$GITHUB_RUN_ID ${{secrets.DOCKER_USER}}/$GITHUB_WORKFLOW:$GITHUB_RUN_ID
          docker image tag $GITHUB_WORKFLOW:$GITHUB_RUN_ID ${{secrets.DOCKER_USER}}/$GITHUB_WORKFLOW:latest

